[package]
name = "ramen"
version = "0.0.1"
authors = ["viri <hi@viri.moe>"]
edition = "2018"

[dependencies]

[features]
default = []
nightly-docs = []

[package.metadata.docs.rs]
features = ["nightly-docs"]
